import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { GitFrameConfig } from './schema';
import { validateConfig } from './validator';
import { ConfigError } from '../common/errors';

export const DEFAULT_CONFIG: GitFrameConfig = {
  project: {
    language: 'node',
    install: 'npm install',
    build: 'npm run build',
    start: 'npm start',
    port: 3000,
    env: {}
  },
  scenarioFile: '.gitframe/demo.yaml',
  outputDir: 'output',
  video: {
    width: 1280,
    height: 720,
    fps: 30
  },
  intro: {
    title: 'GitFrame Demo Recording',
    subtitle: 'Automated Playback',
    duration: 3
  },
  outro: {
    title: 'Thank You',
    subtitle: 'Generated by GitFrame',
    duration: 2
  },
  captions: true
};

export function loadConfig(configPath?: string): GitFrameConfig {
  let fileContent = '';
  if (configPath && fs.existsSync(configPath)) {
    fileContent = fs.readFileSync(configPath, 'utf8');
  } else {
    const defaultPath = path.join(process.cwd(), '.gitframe', 'gitframe.yaml');
    if (fs.existsSync(defaultPath)) {
      fileContent = fs.readFileSync(defaultPath, 'utf8');
    }
  }

  if (!fileContent) {
    return JSON.parse(JSON.stringify(DEFAULT_CONFIG));
  }

  try {
    const parsed = yaml.load(fileContent) as any;
    const validated = validateConfig(parsed);

    const merged: GitFrameConfig = {
      project: {
        ...DEFAULT_CONFIG.project,
        ...(validated.project || {}),
        env: {
          ...(DEFAULT_CONFIG.project?.env || {}),
          ...(validated.project?.env || {})
        }
      },
      scenarioFile: validated.scenarioFile ?? DEFAULT_CONFIG.scenarioFile,
      outputDir: validated.outputDir ?? DEFAULT_CONFIG.outputDir,
      video: {
        ...DEFAULT_CONFIG.video,
        ...(validated.video || {})
      },
      intro: {
        ...DEFAULT_CONFIG.intro,
        ...(validated.intro || {})
      },
      outro: {
        ...DEFAULT_CONFIG.outro,
        ...(validated.outro || {})
      },
      captions: validated.captions ?? DEFAULT_CONFIG.captions
    };

    return merged;
  } catch (err: any) {
    throw new ConfigError(`Failed to load config: ${err.message}`);
  }
}
